# Generated by Django 5.1.6 on 2025-03-04 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=1000)),
                ('journal_category', models.CharField(blank=True, choices=[('Global Journal of Modern Research and Emerging Trends (GJ-MRET)', 'Global Journal of Modern Research and Emerging Trends (GJ-MRET)'), ('International journal of public relations and social sciences (IJPRSS)', 'International journal of public relations and social sciences (IJPRSS)')], max_length=1000, null=True)),
                ('co_authors', models.CharField(blank=True, max_length=1000, null=True)),
                ('article_keywords', models.CharField(max_length=1000)),
                ('article_abstract', models.TextField()),
                ('article_file', models.FileField(upload_to='articles')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
