# Generated by Django 5.1.6 on 2025-03-17 16:18

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=1000)),
                ('journal_cover', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('journal_description', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=1000)),
                ('article_slug', models.SlugField(blank=True, help_text='Leave blank to auto-populate', null=True, unique=True)),
                ('co_authors', models.CharField(blank=True, help_text='seprate each co-authors with comma', max_length=1000, null=True)),
                ('article_keywords', models.CharField(help_text='seprate each keywords with comma', max_length=1000)),
                ('article_abstract', models.TextField()),
                ('article_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('publish', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journal_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.journal')),
            ],
        ),
    ]
