# Generated by Django 5.1.6 on 2025-03-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_journal_journal_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_abbreviation',
            field=models.CharField(help_text='e.g: IJPRSS', max_length=1000),
        ),
    ]
