# Generated by Django 5.1.6 on 2025-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_article_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
