# Generated by Django 5.1.6 on 2025-03-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_journal_journal_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-populate', null=True, unique=True),
        ),
    ]
