# Generated by Django 5.1.6 on 2025-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_journal_journal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_DOI',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_file',
            field=models.FileField(upload_to='articles'),
        ),
    ]
