# Generated by Django 5.1.6 on 2025-03-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_article_article_doi_alter_article_article_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
