# Generated by Django 5.1.6 on 2025-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_article_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
