# Generated by Django 5.1.6 on 2025-03-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_article_article_file_url_alter_article_article_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
