# Generated by Django 5.1.6 on 2025-05-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_journal_journal_issn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_ISSN',
            field=models.CharField(max_length=1000),
        ),
    ]
