# Generated by Django 5.1.6 on 2025-05-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_journal_journal_issn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='volume',
        ),
        migrations.AddField(
            model_name='volume',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text='Volume number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='year',
            field=models.PositiveIntegerField(default=1, help_text='e.g., 2025'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Issue number')),
                ('month', models.CharField(help_text="e.g., 'March', 'May'", max_length=20)),
                ('publish_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dashboard.volume')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.issue'),
        ),
    ]
