# Generated by Django 5.1.6 on 2025-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_volume_volume_volume_number_volume_year_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_volume',
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank to auto-populate', null=True),
        ),
    ]
