# Generated by Django 5.1.6 on 2025-07-09 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_article_article_volume_article_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.issue'),
        ),
    ]
