# Generated by Django 5.1.6 on 2025-08-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_article_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-populate', max_length=1000, null=True, unique=True),
        ),
    ]
