# Generated by Django 5.1.6 on 2026-03-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_article_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_cover',
            field=models.ImageField(upload_to='journal_covers/'),
        ),
    ]
