# Generated by Django 5.1.6 on 2026-03-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_journal_journal_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_file_url',
        ),
    ]
