# Generated by Django 5.1.6 on 2026-03-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_article_article_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_first_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='article_last_page',
            field=models.IntegerField(default=1),
        ),
    ]
