# Generated by Django 5.1.6 on 2026-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_article_article_first_page_article_article_last_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_first_page',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_last_page',
            field=models.IntegerField(),
        ),
    ]
