# Generated by Django 5.1.6 on 2025-03-08 08:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dmpxni4ku/image/upload/v1713334275/user-avatar-placeholder_dfzivc.png', max_length=255, verbose_name='image'),
        ),
    ]
